# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
 - job: Deploy
   displayName: Maven Package and Publish Artifacts
   steps:
   - task: Maven@3
     displayName: 'Maven Package'
     inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
   - task: AzureWebApp@1
     displayName: 'Deploy Azure Web App'
     inputs:
      azureSubscription: 'autobotzi-service-connection'
      appType: 'webAppLinux'
      appName: "atc-2024-autobotzi-be-linux-web-app"
      package: '$(Pipeline.Workspace)/**/target/*.?(war|jar)'